import assert from 'node:assert/strict';
import vm from 'node:vm';
import { readFile } from 'node:fs/promises';
const html = await readFile(new URL('../Index.html', import.meta.url),'utf8');
const core = html.match(/<script>([\s\S]*?)<\/script>/)[1];
const ui = await readFile(new URL('../chronicles.js', import.meta.url),'utf8');
const storage = new Map();
const nodes = new Map();
const makeNode = () => ({style:{},value:'',innerHTML:'',textContent:'',classList:{add(){},remove(){},contains(){return false},toggle(){}},setAttribute(){},appendChild(){},append(){},focus(){},replaceChildren(){},addEventListener(){}});
const document = {body:{dataset:{},scrollHeight:0},addEventListener(){},querySelectorAll(){return []},getElementById(id){if(!nodes.has(id))nodes.set(id,makeNode());return nodes.get(id)},createElement:makeNode};
const context = vm.createContext({document,console:{log(){},warn(){},error(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},crypto:{randomUUID:()=> 'test-session'},window:{scrollTo(){},matchMedia:()=>({matches:false})},alert(){},confirm:()=>true,URL,Blob,setTimeout,clearTimeout,TextDecoder,AbortController});
vm.runInContext(core+'\n'+ui,context);
const run = code => vm.runInContext(code,context);
const data = code => JSON.parse(JSON.stringify(run(code)));
run('renderGameUI=()=>{};updateStatePanel=()=>{};checkSavesUI=()=>{};updateTokenDisplay=()=>{};applySettings=()=>{};appendMessageBlock=()=>({textContent:""}); apiKey="test"; currentModel="test-model";');
const reply = (text,money,lore) => '<текст>'+text+'</текст><выборы>1. А\n2. Б\n3. В\n4. Г</выборы><состояние>'+JSON.stringify({money})+'</состояние><лор>'+JSON.stringify(lore)+'</лор>';
const person = {kind:'person',name:'Илья',description:'Лодочник ждёт героя утром.',certainty:'факт'};
context.firstReply = reply('Илья ждёт у лодки.',30,[person]);
run('gameState={location:"Порт Теней",day:1,money:40,wounds:[],inventory:[],sessionLore:[]}; character={name:"Тест"};chatHistory=[{role:"user",content:"Начало"}];callOpenRouterStream=async()=>({content:firstReply});');
await run('executeTurn(true)');
assert.equal(run('gameState.money'),30);assert.equal(run('gameState.chapter'),1);assert.equal(run('gameState.sessionLore.length'),1);
assert.equal(data('chatHistory[1].stateBefore').money,40);
assert.equal(JSON.parse(storage.get('kordim_save_1')).gameState.sessionLore[0].name,'Илья');
context.nextReply = reply('Сделка состоялась.',25,[{...person,name:'ИЛЬЯ',description:'За переправу получено пять грошей.',certainty:'слух'},{kind:'place',name:'Старая пристань',description:'Место встречи у воды.',certainty:'факт'}]);
run('chatHistory.push({role:"user",content:"Переправа"});callOpenRouterStream=async()=>({content:nextReply});');
await run('executeTurn(false)');
assert.equal(run('gameState.chapter'),2);assert.equal(run('gameState.sessionLore.length'),2);
assert.equal(run('gameState.sessionLore[0].firstChapter'),1);assert.equal(run('gameState.sessionLore[0].certainty'),'слух');
const beforeRewrite=data('gameState');
run('callOpenRouterStream=async()=>{throw Error("Проверка отказа провайдера")};');
await run('executeTurn(false,true)');
assert.deepEqual(data('gameState'),beforeRewrite,'Failed rewrite must keep all existing memory and state');assert.equal(run('isTurnRunning'),false);
context.alternative=reply('Другая встреча.',19,[{kind:'person',name:'Анна',description:'Предложила работу.',certainty:'факт'}]);
run('callOpenRouterStream=async()=>({content:alternative});');await run('executeTurn(false,true)');
assert.equal(run('gameState.sessionLore.length'),2);assert.equal(run('gameState.sessionLore.some(e=>e.name==="Старая пристань")'),false);
run('changeSwipe(-1)');assert.equal(run('gameState.money'),25);assert.equal(run('gameState.sessionLore.some(e=>e.name==="Старая пристань")'),true);
run('changeSwipe(1)');assert.equal(run('gameState.money'),19);assert.equal(run('gameState.sessionLore.some(e=>e.name==="Анна")'),true);
run('undoTurn()');assert.equal(run('gameState.money'),30);assert.equal(run('gameState.sessionLore.length'),1);assert.equal(run('gameState.chapter'),1);
run('gameState.sessionLore=[];loadGame(1)');assert.equal(run('gameState.sessionLore.length'),1);
storage.set('kordim_save_2',JSON.stringify({character:{name:'Старый герой'},gameState:{money:7,day:1,location:'Столица',wounds:[],inventory:[]},chatHistory:[]}));
run('loadGame(2)');assert.equal(run('gameState.sessionLore.length'),0);assert.equal(run('gameState.money'),7);
assert.equal(run('parseResponse("<текст>Сцена<лор>[invalid").text'),'Сцена');assert.equal(run('parseResponse("<текст>Сцена</текст><лор>не JSON</лор>").loreDelta.length'),0);
context.invalid=[{kind:'person',name:'Пустой',description:''},{kind:'wrong',name:'Х',description:'Х'},null];assert.equal(run('normalizeLore(invalid).length'),0);
run('gameState={money:0,sessionLore:[]};applySessionLore([{kind:"fact",name:"Версия",description:"Не подтверждено"}],1)');assert.equal(run('gameState.sessionLore[0].certainty'),'предположение');
run('isDemo=true;activeSlot=0;saveGame()');assert.equal(storage.has('kordim_save_0'),false);
run('isDemo=false;gameState={money:0,day:1,sessionLore:[]};chatHistory=[{role:"user",content:"Тест"}];');
let complete;let calls=0;context.mockStream=()=>{calls++;return new Promise(resolve=>complete=resolve)};run('callOpenRouterStream=mockStream');
const pending=run('executeTurn(true)');await run('executeTurn(true)');assert.equal(calls,1,'Double submit must issue one request');complete({content:context.firstReply});await pending;assert.equal(run('isTurnRunning'),false);
run('activeSlot=1;storyArchive=[];chatHistory=Array.from({length:18},(_,i)=>({role:i%2?"assistant":"user",content:"archive-"+i,chapter:i%2?Math.floor(i/2)+1:undefined}));callOpenRouter=async()=>({choices:[{message:{content:"[]"}}]});');
await run('summarizeHistory()');
assert.equal(run('storyArchive.length'),10);assert.equal(run('chatHistory.length'),8);
assert.equal(run('storyArchive[0].content'),'archive-0');
run('saveGame();storyArchive=[];loadGame(activeSlot)');assert.equal(run('storyArchive.length'),10);
context.captureStream=async messages=>{context.captured=messages;return {content:context.firstReply}};
run('storyArchive=[];chatHistory=[{role:"user",content:"Илья"}];gameState={money:40,day:1,location:"Порт Теней",sessionLore:[{kind:"person",name:"Илья",description:"Ждёт у лодки.",certainty:"факт",firstChapter:1,lastChapter:1,day:1}],direction:"Спокойный разговор"};callOpenRouterStream=captureStream');
await run('executeTurn(false)');
const tail=context.captured.at(-1).content;
assert.ok(tail.includes('ПАМЯТЬ ЭТОЙ СЕССИИ'));assert.ok(tail.includes('Спокойный разговор'));assert.ok(!tail.includes('"sessionLore"'),'Avoid sending entire lore twice');
console.log('PASS: lore extraction, status and deduplication; save/load and legacy save; failed rewrite; swipe and undo snapshots; malformed tags; demo isolation; duplicate-submit lock.');
